// flow-typed signature: 8fd7e14dec213184140f80e416f28033
// flow-typed version: <<STUB>>/template-string-loader_v^0.0.3/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'template-string-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'template-string-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'template-string-loader/index' {
  declare module.exports: $Exports<'template-string-loader'>;
}
declare module 'template-string-loader/index.js' {
  declare module.exports: $Exports<'template-string-loader'>;
}
